"""Email delivery of the memo over SMTP.

Uses Python's standard library (smtplib + email) so there is no third-party
dependency and the same code runs identically for a local run and the scheduled
GitHub Actions run. The only external piece is Markdown → HTML rendering for a
readable email body; the original Markdown is attached as a file.

Credentials never appear here — they arrive via EmailConfig, which reads them
from the environment (.env locally, Actions secrets in CI).
"""

from __future__ import annotations

import smtplib
import ssl
from email.message import EmailMessage
from typing import Any, Dict, List

import markdown as _markdown

from .config import EmailConfig

_SUBJECT_PREFIX = "Infra Legal Radar"

# Minimal, email-client-friendly styling. Gmail keeps a <style> block in <head>,
# and the layout degrades gracefully to plain readable text elsewhere.
_HTML_TEMPLATE = """\
<!doctype html>
<html>
<head>
<meta charset="utf-8">
<style>
  body {{ font-family: -apple-system, Segoe UI, Roboto, Helvetica, Arial, sans-serif;
         line-height: 1.5; color: #1a1a1a; max-width: 760px; margin: 0 auto; padding: 16px; }}
  h1 {{ font-size: 20px; border-bottom: 2px solid #ddd; padding-bottom: 6px; }}
  h2 {{ font-size: 17px; margin-top: 28px; }}
  h3 {{ font-size: 15px; margin-top: 22px; }}
  blockquote {{ border-left: 3px solid #ccc; margin: 8px 0; padding: 2px 12px; color: #444; }}
  code {{ background: #f2f2f2; padding: 1px 4px; border-radius: 3px; }}
  hr {{ border: none; border-top: 1px solid #e0e0e0; margin: 24px 0; }}
  em {{ color: #555; }}
  ul {{ padding-left: 22px; }}
</style>
</head>
<body>
{body}
<hr>
<p style="font-size:12px;color:#888">Generated by Infrastructure Legal Event Radar.
The full memo is attached as a Markdown file.</p>
</body>
</html>
"""


def build_subject(
    items: List[Dict[str, Any]], out_of_region_events: List[Dict[str, Any]] = None
) -> str:
    """Summarize triage counts in the subject line.

    Only URGENT and REVIEW are 'material'; NOISE / out-of-region are not counted
    here. If nothing material, the subject reads 'all quiet'.
    Examples: 'Infra Legal Radar: 1 URGENT, 3 REVIEW' / 'Infra Legal Radar: all quiet'.
    """
    urgent = sum(1 for it in items if it.get("memo", {}).get("materiality") == "URGENT")
    review = sum(1 for it in items if it.get("memo", {}).get("materiality") == "REVIEW")
    failed = sum(1 for it in items if "memo" not in it)

    parts = []
    if urgent:
        parts.append(f"{urgent} URGENT")
    if review:
        parts.append(f"{review} REVIEW")

    summary = ", ".join(parts) if parts else "all quiet"
    subject = f"{_SUBJECT_PREFIX}: {summary}"
    if failed:
        subject += f" (+{failed} error{'s' if failed != 1 else ''})"
    return subject


def render_html(memo_markdown: str) -> str:
    """Convert the memo Markdown to a styled HTML document for the email body."""
    body = _markdown.markdown(
        memo_markdown, extensions=["extra", "sane_lists", "nl2br"]
    )
    return _HTML_TEMPLATE.format(body=body)


def send_memo_email(
    cfg: EmailConfig,
    *,
    subject: str,
    memo_markdown: str,
    attachment_name: str,
) -> None:
    """Send the memo: HTML body + plain-text fallback + Markdown attachment.

    Raises on failure (auth, connection) so the caller can report it; the caller
    is responsible for deciding that a failed send should not sink the whole run.
    """
    missing = cfg.missing_credentials()
    if missing:
        raise RuntimeError(
            "Email not sent — missing credential(s): "
            + ", ".join(missing)
            + ". Set them in .env (local) or GitHub Actions secrets (CI)."
        )

    msg = EmailMessage()
    msg["Subject"] = subject
    msg["From"] = cfg.from_addr
    msg["To"] = cfg.to
    # Plain-text fallback = the raw Markdown (already human-readable).
    msg.set_content(memo_markdown)
    msg.add_alternative(render_html(memo_markdown), subtype="html")
    msg.add_attachment(
        memo_markdown.encode("utf-8"),
        maintype="text",
        subtype="markdown",
        filename=attachment_name,
    )

    context = ssl.create_default_context()
    with smtplib.SMTP(cfg.smtp_host, cfg.smtp_port, timeout=30) as server:
        server.starttls(context=context)
        server.login(cfg.username, cfg.password)
        server.send_message(msg)
